---
kind: pipeline
type: ssh
name: Deploy

server:
  host:
    from_secret: HOST_ADDR
  user:
    from_secret: USER
  password:
    from_secret: PASSWORD

steps:
- name: Deploy via docker
  environment:
    BACKEND_ENDPOINT:
      from_secret: BACKEND_ENDPOINT
    BACKEND_TOKEN:
      from_secret: BACKEND_TOKEN
    DOMAIN_NAME:
      from_secret: DOMAIN_NAME
  commands:
    - docker-compose up -d --build --force-recreate