const BACKEND_ENDPOINT = process.env.BACKEND_ENDPOINT!;
const BACKEND_TOKEN = process.env.BACKEND_TOKEN!;
const GRAPHQL_ENDPOINT = `${BACKEND_ENDPOINT}/graphql`;
const ASSETS_ENDPOINT = `${BACKEND_ENDPOINT}/assets`;

export const ENV_VARS = {
  BACKEND_ENDPOINT,
  GRAPHQL_ENDPOINT,
  ASSETS_ENDPOINT,
  BACKEND_TOKEN,
};
